CREATE TYPE "WalletType" AS ENUM ('CASH', 'BANK_ACCOUNT', 'E_WALLET', 'CREDIT_CARD', 'SAVINGS', 'OTHER');

ALTER TABLE "wallets"
ALTER COLUMN "type" TYPE "WalletType"
USING (
  CASE "type"
    WHEN 'CASH' THEN 'CASH'
    WHEN 'BANK_ACCOUNT' THEN 'BANK_ACCOUNT'
    WHEN 'E_WALLET' THEN 'E_WALLET'
    WHEN 'CREDIT_CARD' THEN 'CREDIT_CARD'
    WHEN 'SAVINGS' THEN 'SAVINGS'
    WHEN 'OTHER' THEN 'OTHER'
    WHEN 'Tien mat' THEN 'CASH'
    WHEN 'Ngan hang' THEN 'BANK_ACCOUNT'
    WHEN 'Vi dien tu' THEN 'E_WALLET'
    ELSE 'OTHER'
  END
)::"WalletType";
